#!/usr/bin/env ruby

host = ARGV[0]
port = ARGV[1]
# puts "connected to: #{host}:#{port}"
system("telnet #{host} #{port}")


# require 'socket'        # Sockets are in standard library

# hostname = 'localhost'
# port = 3939

# s = TCPSocket.open(hostname, port)
# vote = 3
# while line = s.gets     # Read lines from the socket
#   puts vote
#   # puts line.chop       # And print with platform line terminator
# end
# s.close


# /home/milan/.cargo/bin:/home/milan/.cargo/bin:/home/milan/.rvm/gems/ruby-2.6.0/bin:/home/milan/.rvm/gems/ruby-2.6.0@global/bin:/home/milan/.rvm/rubies/ruby-2.6.0/bin:/home/milan/bin:/home/milan/.local/bin:/home/milan/.cargo/bin:/home/milan/bin:/home/milan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/milan/.rvm/bin:/home/milan/.rvm/bin:/home/milan/.rvm/bin